---
# A simple example that utilizes the uri module to make a REST call to a vRA
# instance to retrieve a bearer token.
- hosts: vrops
  tasks:
   - name: Get a Bearer Token
     uri:
       validate_certs: false
       url: https://vra-01a.corp.local/identity/api/tokens
       method: POST
       body: "{\"username\":\"jason\",\"password\":\"VMware1!\",\"tenant\":\"vsphere.local\"}"
       headers:
         Accept: "application/json"
         Content-Type: "application/json"
       return_content: yes
     register: bearer

   - debug: msg="{{ bearer.content }}"
