---
# hosts could have been "remote" or "all" as well
- hosts: vrops
  gather_facts: no
  tasks:
   - name: Get a Bearer Token
     vrarest:
       host: vra-01a.corp.local
       rest_method: get_bearer_token
       username: jason
       password: VMware1!
       tenant: vsphere.local

     register: bearer_result

   - debug: msg="The returned token is {{ bearer_result.token }}"

   - name: Get the Catalog Items
     vrarest:
       host: vra-01a.corp.local
       rest_method: get_catalog_items
       token: "{{ bearer_result.token }}"

     register: catalog_items_result

#   - debug: msg="The response is {{ catalog_items_result }}"
#   - debug: msg="The content is {{ catalog_items_result['response_json'] }}"
#   - debug: msg="The ID for the CentOS 6.3 blueprint is {{ catalog_items_result['response_json'].content[0].catalogItemId }}"

   - name: Iterate over catalog items to find the blueprint
     debug:
       msg: "Item \\: {{ item.catalogItemId }}"
     with_items: "{{ catalog_items_result['response_json'].content }}"
     when: item.name == "SQL 2016 Standard Standalone"
