---
# This example makes a call to the vravm module to create a VM with just basic
# parameters specified.
- hosts: vrops
  tasks:
   - name: Create a VM
     vravm:
       host: vra-01a.corp.local
       username: jason
       password: VMware1!
       tenant: vsphere.local
       blueprint_name: "CentOS 6.3"
       memory: 1024
       cpu_count: 2
       num_of_instances: 1

     register: vravm_result

   - debug:
       msg: "Output: {{ vravm_result['output'] }}"
